name = "Rouwenhorst"
uuid = "aa6e03af-5005-41e9-ae6d-aa2507035e62"
authors = ["Eirik Eylands Brandsaas <eirikeb@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
